"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 15:30:52.850517
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cities')),
    sa.UniqueConstraint('name', 'country_code', name=op.f('uq_cities_name_country_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Enum('CUSTOMER', 'PROVIDER', 'ADMIN', name='role_code', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('services',
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_sw', sa.String(length=120), nullable=False),
    sa.Column('summary_en', sa.String(length=255), nullable=False),
    sa.Column('summary_sw', sa.String(length=255), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_sw', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('uses_rooms', sa.Boolean(), nullable=False),
    sa.Column('included_bedrooms', sa.Integer(), nullable=False),
    sa.Column('included_bathrooms', sa.Integer(), nullable=False),
    sa.Column('price_per_extra_bedroom', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_per_extra_bathroom', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minutes_per_extra_room', sa.Integer(), nullable=False),
    sa.Column('max_rooms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_duration_minutes > 0', name=op.f('ck_services_duration_positive')),
    sa.CheckConstraint('base_price >= 0', name=op.f('ck_services_base_price_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('slug', name=op.f('uq_services_slug'))
    )
    op.create_table('service_areas',
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('fk_service_areas_city_id_cities'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_areas')),
    sa.UniqueConstraint('city_id', 'name', name=op.f('uq_service_areas_city_id_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_service_areas_slug'))
    )
    op.create_index(op.f('ix_service_areas_city_id'), 'service_areas', ['city_id'], unique=False)
    op.create_table('service_options',
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('group', sa.Enum('PROPERTY_TYPE', 'SIZE', 'ADDON', name='option_group', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_sw', sa.String(length=120), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_quantity >= 1', name=op.f('ck_service_options_max_quantity_positive')),
    sa.CheckConstraint('price_amount >= 0', name=op.f('ck_service_options_price_non_negative')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_options_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_options')),
    sa.UniqueConstraint('service_id', 'code', name=op.f('uq_service_options_service_id_code'))
    )
    op.create_index(op.f('ix_service_options_service_id'), 'service_options', ['service_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferred_locale', sa.String(length=5), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('customers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('default_area_id', sa.Uuid(), nullable=True),
    sa.Column('default_address', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_area_id'], ['service_areas.id'], name=op.f('fk_customers_default_area_id_service_areas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_customers_user_id'))
    )
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_platform_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_platform_settings'))
    )
    op.create_table('providers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_type', sa.Enum('INDIVIDUAL', 'COMPANY', name='provider_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=60), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verification_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_accepting_jobs', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity >= 1', name=op.f('ck_providers_capacity_positive')),
    sa.CheckConstraint('rating_count >= 0', name=op.f('ck_providers_rating_count_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_providers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_providers_user_id'))
    )
    op.create_index(op.f('ix_providers_verification_status'), 'providers', ['verification_status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_CONFIRMATION', 'CONFIRMED', 'FINDING_PROVIDER', 'PROVIDER_ASSIGNED', 'PROVIDER_EN_ROUTE', 'PROVIDER_ARRIVED', 'SERVICE_IN_PROGRESS', 'COMPLETED_BY_PROVIDER', 'CUSTOMER_CONFIRMED', 'CLOSED', 'CANCELLED', 'REASSIGNMENT_REQUIRED', 'DISPUTED', name='booking_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('property_type_option_id', sa.Uuid(), nullable=True),
    sa.Column('size_option_id', sa.Uuid(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_start_time', sa.Time(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('service_name_snapshot', sa.String(length=120), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('adjustments_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider_earning', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'MOBILE_MONEY', 'CARD', name='payment_method', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bedrooms >= 0 AND bathrooms >= 0', name=op.f('ck_bookings_rooms_non_negative')),
    sa.CheckConstraint('commission_amount + provider_earning = total_amount', name=op.f('ck_bookings_economics_balance')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_bookings_total_non_negative')),
    sa.ForeignKeyConstraint(['area_id'], ['service_areas.id'], name=op.f('fk_bookings_area_id_service_areas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_bookings_customer_id_customers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_type_option_id'], ['service_options.id'], name=op.f('fk_bookings_property_type_option_id_service_options'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_bookings_provider_id_providers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_bookings_service_id_services'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['size_option_id'], ['service_options.id'], name=op.f('fk_bookings_size_option_id_service_options'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('reference', name=op.f('uq_bookings_reference'))
    )
    op.create_index(op.f('ix_bookings_area_id'), 'bookings', ['area_id'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_bookings_provider_id'), 'bookings', ['provider_id'], unique=False)
    op.create_index('ix_bookings_provider_schedule', 'bookings', ['provider_id', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_bookings_scheduled_date'), 'bookings', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_bookings_service_id'), 'bookings', ['service_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('provider_availability',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name=op.f('ck_provider_availability_valid_day')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_provider_availability_valid_window')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_availability_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_availability')),
    sa.UniqueConstraint('provider_id', 'day_of_week', name=op.f('uq_provider_availability_provider_id_day_of_week'))
    )
    op.create_index(op.f('ix_provider_availability_provider_id'), 'provider_availability', ['provider_id'], unique=False)
    op.create_table('provider_service_areas',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['service_areas.id'], name=op.f('fk_provider_service_areas_area_id_service_areas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_service_areas_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_id', 'area_id', name=op.f('pk_provider_service_areas'))
    )
    op.create_index(op.f('ix_provider_service_areas_area_id'), 'provider_service_areas', ['area_id'], unique=False)
    op.create_table('provider_services',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_services_provider_id_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_provider_services_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_id', 'service_id', name=op.f('pk_provider_services'))
    )
    op.create_index(op.f('ix_provider_services_service_id'), 'provider_services', ['service_id'], unique=False)
    op.create_table('provider_verifications',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('SUBMITTED', 'APPROVED', 'REJECTED', 'SUSPENDED', 'REACTIVATED', name='verification_decision', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_verifications_provider_id_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_provider_verifications_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_verifications'))
    )
    op.create_index(op.f('ix_provider_verifications_provider_id'), 'provider_verifications', ['provider_id'], unique=False)
    op.create_table('booking_price_items',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('label_en', sa.String(length=160), nullable=False),
    sa.Column('label_sw', sa.String(length=160), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_price_items_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['service_options.id'], name=op.f('fk_booking_price_items_option_id_service_options'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_price_items'))
    )
    op.create_index(op.f('ix_booking_price_items_booking_id'), 'booking_price_items', ['booking_id'], unique=False)
    op.create_table('booking_status_history',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING_CONFIRMATION', 'CONFIRMED', 'FINDING_PROVIDER', 'PROVIDER_ASSIGNED', 'PROVIDER_EN_ROUTE', 'PROVIDER_ARRIVED', 'SERVICE_IN_PROGRESS', 'COMPLETED_BY_PROVIDER', 'CUSTOMER_CONFIRMED', 'CLOSED', 'CANCELLED', 'REASSIGNMENT_REQUIRED', 'DISPUTED', name='from_booking_status', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING_CONFIRMATION', 'CONFIRMED', 'FINDING_PROVIDER', 'PROVIDER_ASSIGNED', 'PROVIDER_EN_ROUTE', 'PROVIDER_ARRIVED', 'SERVICE_IN_PROGRESS', 'COMPLETED_BY_PROVIDER', 'CUSTOMER_CONFIRMED', 'CLOSED', 'CANCELLED', 'REASSIGNMENT_REQUIRED', 'DISPUTED', name='booking_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('changed_by_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_status_history_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], name=op.f('fk_booking_status_history_changed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_status_history'))
    )
    op.create_index(op.f('ix_booking_status_history_booking_id'), 'booking_status_history', ['booking_id'], unique=False)
    op.create_table('complaints',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('QUALITY', 'LATE_OR_NO_SHOW', 'DAMAGE', 'CONDUCT', 'PAYMENT', 'OTHER', name='complaint_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'RESOLVED', 'REJECTED', name='complaint_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_complaints_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_complaints_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_complaints_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints'))
    )
    op.create_index(op.f('ix_complaints_booking_id'), 'complaints', ['booking_id'], unique=False)
    op.create_index(op.f('ix_complaints_customer_id'), 'complaints', ['customer_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'SMS', 'PUSH', name='notification_channel', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('booking_reference', sa.String(length=16), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_notifications_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'MOBILE_MONEY', 'CARD', name='payment_method', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', 'CANCELLED', name='payment_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by_id', sa.Uuid(), nullable=True),
    sa.Column('gateway', sa.String(length=40), nullable=False),
    sa.Column('gateway_reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_payments_amount_non_negative')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], name=op.f('fk_payments_confirmed_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_payments_booking_id'))
    )
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('provider_assignments',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OFFERED', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED', 'WITHDRAWN', name='assignment_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('offered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_note', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_provider_assignments_assigned_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_provider_assignments_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_assignments_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_assignments'))
    )
    op.create_index('ix_assignments_provider_status', 'provider_assignments', ['provider_id', 'status'], unique=False)
    op.create_index(op.f('ix_provider_assignments_booking_id'), 'provider_assignments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_provider_assignments_expires_at'), 'provider_assignments', ['expires_at'], unique=False)
    op.create_table('provider_settlements',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider_earning', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_collected_by_provider', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SETTLED', name='settlement_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_by_id', sa.Uuid(), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_provider_settlements_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_provider_settlements_provider_id_providers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['settled_by_id'], ['users.id'], name=op.f('fk_provider_settlements_settled_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_settlements')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_provider_settlements_booking_id'))
    )
    op.create_index(op.f('ix_provider_settlements_provider_id'), 'provider_settlements', ['provider_id'], unique=False)
    op.create_index(op.f('ix_provider_settlements_status'), 'provider_settlements', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('moderation_note', sa.String(length=255), nullable=True),
    sa.Column('moderated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_reviews_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_reviews_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderated_by_id'], ['users.id'], name=op.f('fk_reviews_moderated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_reviews_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_reviews_booking_id'))
    )
    op.create_index(op.f('ix_reviews_customer_id'), 'reviews', ['customer_id'], unique=False)
    op.create_index(op.f('ix_reviews_provider_id'), 'reviews', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_provider_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_customer_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_provider_settlements_status'), table_name='provider_settlements')
    op.drop_index(op.f('ix_provider_settlements_provider_id'), table_name='provider_settlements')
    op.drop_table('provider_settlements')
    op.drop_index(op.f('ix_provider_assignments_expires_at'), table_name='provider_assignments')
    op.drop_index(op.f('ix_provider_assignments_booking_id'), table_name='provider_assignments')
    op.drop_index('ix_assignments_provider_status', table_name='provider_assignments')
    op.drop_table('provider_assignments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_customer_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_booking_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_booking_status_history_booking_id'), table_name='booking_status_history')
    op.drop_table('booking_status_history')
    op.drop_index(op.f('ix_booking_price_items_booking_id'), table_name='booking_price_items')
    op.drop_table('booking_price_items')
    op.drop_index(op.f('ix_provider_verifications_provider_id'), table_name='provider_verifications')
    op.drop_table('provider_verifications')
    op.drop_index(op.f('ix_provider_services_service_id'), table_name='provider_services')
    op.drop_table('provider_services')
    op.drop_index(op.f('ix_provider_service_areas_area_id'), table_name='provider_service_areas')
    op.drop_table('provider_service_areas')
    op.drop_index(op.f('ix_provider_availability_provider_id'), table_name='provider_availability')
    op.drop_table('provider_availability')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_service_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_scheduled_date'), table_name='bookings')
    op.drop_index('ix_bookings_provider_schedule', table_name='bookings')
    op.drop_index(op.f('ix_bookings_provider_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_area_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_providers_verification_status'), table_name='providers')
    op.drop_table('providers')
    op.drop_table('platform_settings')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_options_service_id'), table_name='service_options')
    op.drop_table('service_options')
    op.drop_index(op.f('ix_service_areas_city_id'), table_name='service_areas')
    op.drop_table('service_areas')
    op.drop_table('services')
    op.drop_table('roles')
    op.drop_table('cities')
    # ### end Alembic commands ###
